language: node_js
node_js:
- 14
sudo: false
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: pLeeiwiL7AzRQOeFPVGUYoU5DTZ48yZ76ZIg+hoGFoxMPbRStkdqKqhoQDf5eeoTEkEj+EAhffP1KPqO9bnTGArW7HFpmngldPlvzdsvvB/zHEJ5CAiwTOyYy1QJ2jeMXIYAQkGczE2d5fcyJ62/R+h4RdOl9407hBaDm9jiXSubUN/851u8V3mqeUcsKbotgNhst1egBEqdcowjgFNVLFNxfV2xqG5Hj3a92BNc0hyCan2Pjj6+vBVgsmy0T2Yl3rdYZuQENjdGhbaQCaL2h0Smz4tPV5lX+eqXwRrAHXi6DUdWu28o5bs0+aqDuctZfv43Lx5Jjk0X7wtEAcq3rgSiHVLnSYQE1kOmARXfgs5AdO+dQ1OpAy4+GymUf0DuRRyxvbaBaEQXr1rHofsqF504LkjM+4tE3ZLwQsxdawTktB9xG+NZC4ABKvo0RopcmakoyBSBbOA9KwY4TnWU3x/ej18HWSNbeSfPEHWyLt/RFFtsUfECgGKcfdV9ScdXRpVE1IHz0b8mOFpbx8vjL18IHL9BrjaHMr2StQ07T53/gkZWj9GTF8KAJawE6wvyfvcssfnaOejeg2qfhro0JS376TrywakvY2AmQ044vGZE07EcWaEgNOj6lVPQob4+8sYn8N+sP6QvWgPip3b3F7fP1at47kTQ59OB0WpVC5M=
  app: devops-ultimate
  edge: true
