language: node_js
node_js:
- 14
sudo: false
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: dczjHRn9qg4yybkhPRYj46i5ZDgaz1/uCg142U0wWPimyjmReL6g7ZGVfn7Bc/guNyWbOX6JoYEe6baHkar0BNvPvifIEPXuWt0y6cFtJ7edKoB6pPMWC1RCl+mI2IROPgEnmC68TID0477A7n+vwo8RrchKPFYat558/cf/NmkhDV0rIVpaOsUQXpVhHmSQcNQw7mIwZsZNUFHT87ehn21+5PBclTwRbfbaOps2yczVOhD8vELYUYM721hRSsF0OqsLfDB4ol2pbBZd0XjawGCJiIXgLsEMBNZvebicx2eyjUA/IvoDYCWh7eI1GJDN3LWyPrEeG9haqCxN92w5+0ltFl9bQGTMP/4j194EAa3yl5KsReDjVih1aHAPuo/rMvpDOXmV3Cak1KxEuwGb+A6hUo+WIfi7Ao6dN2By7hluOjH9fiTYQmN5r4c4L6YAyA218GC+3SUVAFfeE4dPJ4ljriNj4cCJ+M52jRmNgy8yIbmXp+8KUyPmHtJWOnkM2IRd020/QkXQeNJjoOalUQNuHfVnmWxIKQbgmhk+GWr4afx2p3IDfRoYLuDx8jblZdC5PeZCLYYkfPDFzpS2bG3H/ciCKcl7ICj1h7udYgEdNWxwlSWd2qkbfNJwqJREeVbTT+IAi0l0HdJ7ulnzXmoPS/tfGemyEI8alfOtdcc=
  app: devops-ultimate
  edge: true
