language: node_js
node_js:
- 16
sudo: false
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: bfQcJmnjpZdkSuZDIiuTrjNr17ApLvTAnsVBD+mlaDz+QJJbKfz91AtvDCpqJg9yjFL/m/3NWRuRq0wqPayKVl/B9Xwl9f7s6a79H8fnZ4sFbS73/zWOa/pJEiH5ur5kEKF2QYKvvzhz0w7n20zZKQYx+sJH/mQEcaGsTeU1jnQUdpvf8U9KaMhaPiE3vXKmfo//kGxhzGV1ZYXKbr3PIbkAM0Gb/NS9eK6k1mdJLLHcZ9VvE4V/CyF5QUqugqN6IrVOSYk2fB4QBY9G5gDbBMC1JbqN5ttVPZy2cdcmwWDLHpgMelHSE49mMuzXveZHCowFeFZhTF5QosB7J+ZjCvD3X/YDkUwcU6qdMgbyy2h396odxUK4exS3RRElaWCow1/l/T0MUbzatolEzJO09ltKLHdWwMKbkcIHQAz/PtahUWQjGNuXlDNJJWhjINab9sMNhMUFNcQzJpYk83jmTgS7IGqQl1W0G/ntXLqi254AGYaaaBhWM8Oyt2Xy7nCmTMY/bkL2OSYQSVzlKTToba0yb/jhJX5WagQcnAE2MgSjlEsK05uAN+YmfqU58P2ALsNaZYsCk+SB3PvwQRLAJy01lW+jnFfPVmlBZhWSscO8ywGU+LLPBQ9qzNGpsnjeRMqbtmEYkaLuC4RVGjbfkWayckZe3a/WHIa4uH0FajU=
  app: devops-ultimate
  edge: true
