language: node_js
node_js:
- 14
sudo: false
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: TNMarAhmipR3fMAb75eBNFpEnKBJeLh7nb91Lhs0oV/FjcLRL30jjUjFy2ah56Gj1y88y9wdtQPn46TNYO++fZ949hS+YqqKh88X/CBuMW2W+Af1NSZ/ZyN4artDW/YUsIOMsg0tBTSVNVIPsdXr4rQ1U4YNIpC2Wqmr2NzkkvYVW95UffUNC34wP9+qY6gL4ITKNwd2EdMJJDDmp4Sv1/RpXrYX4PXgZmqFUgum2ie66ivagwHAKLlqCJPGC8+nBRigrM3AllEycjWkCg5RV5QDjzrA73ef77aIEXvTWeuOJGelM1PdAihxCZkvd7ZGc7+bCpY/rLdT2kJ/E2asoMCFwikANvmuXsZ54w32ZVlM4ci+qpyMmzoTw1TQ9wYx1pFfsNwalt6p5ZI7ILVZHOZ5348u+GXnFFx273a0woEG55s+fGKWNp90v+d6wm+uIEqwV0v4XddctZVh7bTxcA2PqUxQWeBUO4piBRpPv6OhhON6R19gSBSNIrsIpUF7/L0DatnmCJb1oUCeY4ovk5tuC/A0J7q02/93i1N5KDBZ+jVhIpFXlZKfWk7MbJzVKX/5FoUUf9VQni/pv6LmrWItRz1Hv5QDYjltKx3yUOKwnzxyLxKCiwvnjfPDP3bE1IybvPekNWXcuzm4rRGFWvATYvFqc4Q07EvTLg2kba0=
  app: devops-ultimate
  edge: true
