language: node_js
node_js:
- 16
sudo: false
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: aLIZtyr8yPdMdtq3IcRtxiZREcebS3UVQeJbOCBOKCFj1y51HQVpKbbwCb+XO9aj7cchYmmfPsv86l6ncQcZO6YgZ/OS02tnRvQW9fIYDuArDYhD/93kq90p2nbrLnCPkn0iQ230pnewSl9r9RzoTb0oiT0wr9d9TWpxXsvoN+B1X1wGPlpaWZ1YzQUnx2nsI6XJPXFO2W0sC4TmLhF2pxV5nJ+yXbxrmToxrH2+TiMnSI7FQ89UjOUnA+eXOP/anDZW99bYKIjSMtHpuVw0iySVYqutyl+QpgFqa/jeGMFSG04Y/Rfpuek3QAA7GMDxVbiNSIdf1NVXK26ECk+5GXvqyl/nTq2xLKaLLK86JsOeT7c3jhbJiEOvQwHSE9s+xkvNfPOu/0ElAwfqONeQfNOeK0mpl2GpaZVZFhwlGiCyI7axc81xp8kKf+4qN0GazclmHqoRugaoADPKHZ/HMCwQaRUfGwPiqmq3q/Hfs69nuhOnIENefxRasfeLVbVHfiNu1XjelMwCxyg126e8ZxXq4zI22VDzv9/W7Fb6YN5uPPsHT0nM/+sZ9TLl2iByZKoUc3hFiSBUzoYjGzqOJTcfHXGQZywAWrKsaROVvrwr1dL/iY7t/ioNG48tbpt2Ww0270GcRpTL6Amqqb6+PMBKostSW+GZjpm8qVXXtEw=
  app: devopspratica
  edge: true
