language: node_js
node_js:
- 14
sudo: false
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: MKu3Tu7CgEtyAb4s+bXv3kJaR6DYE5KEyHpX2BJzKthMYaggEOaMUg9jfgNgn+Uja2+KhsyokJ29G7QjsE+sj+45PzoE7dr0ZaANZRbsrXUkdR6pU6MAnTa1R2ARLDVLRlbZksmYH17upY+fcTDEzBs2WS0YA1Neikq06VM+gH5KG8CZ1mwG9P1r/ywCiNzGjTWtlTcAGVzMvi4xuzX65ckcARDAeUq2v209/p7GMG60fnf4yYXKZ97KlmohEOtKvwLGT805Mmt/lzcWb9CeEKbJ0QVToZaatAjHoUrJ4/vKp+ggek72sVZrsszRkAX4OWW9FgpCzY/UQ1B2rYCzXdQgUovyLuZ7kXjRtGBwwmObHT/99oCNZ8CAhHeRNl4lCK/efZkDG064bODrIrtzxhYzt45C7mU2QO63ApeYm8WelLxZgJEAH9twlnkB6yuiA1v6dRch38UUrCaETCIh9/7rCUIlI3rUmNbu4Fhv4t0eSxCydUTB7JHmkATY+fVn4xHtfH63Cbik1kbZjl6YXgPLdMfQjiH9dYw863GQeaGf1DkEklAcZslItN6N7E/olR9doGJhkX4Un9CTpaORHWbGs/afKze/PSZiVeW2wVPWDGoLvAPk9Q5rSoDDP40oMwjuGGlhR65k0LNN/UAY8/r8Pgdm+7RGU8oOlploaOc=
  app: devops-ultimate
  edge: true
