language: node_js
node_js:
- 14
sudo: false
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: pg25x+vDdjRM37cEeVClcwYx6JQ1KxQ2/2KnvydCiINAFoW93A6f1ynv+VOziYKnNmvqAilclHQxkAcBW/XnZjqkX2ue3MUKXSXCbVlXdTG1RHNA33EvnZQpp8xRdlKorR7Ct7ES34iI8n8DKSFQQSsLJZC6Y3mdKrqxA0Yh/q5nai4BEGc3vLJhbi9+j6W/tVygdEJo+nrqyiKvzR0MvuQ5M9h2enV8dzXIT1EjVFl6F0kvYDQtRFut7FrPS3ckvftwuIeg0PKkdpslZD/3+6rlxQSjENL/Ym+CGPwIvR1h+JRDZpNOFiX4Qak3G7PO1AYBj7F7kT+mdAjwkZP2Kfa+XmOXE8/NHcV5HZs+VKrcDyS54TiOaz5LiUKMNVGB/ZMNovA5y9eAiK4zCLtNU7JK3HfJnpFVy7PcLbtb3Klv1aZJ662WMZlFLLG7eD6MII2XQ0wHXVpWWoxJ+pRshggxvJhamm8X0fYzVaULkq/Lj08ZXqV06BlOQfqqjvAYRxLaWN79GqnwFJqVdIqFQiwfQmjdSPuVNDd5nAXa19t5XIQly3R/J15F03fQZ0WQ06A6qCm1BOQTsiWsFfRuS2CCdPlrQSPc4SNwF1oF2UDnWETXTDsn5v7s/zv1BO90WwvesP1c0eNsKmm5V5G8HAyD3pt1WkCT4x4VoLQAwVU=
  app: devops-ultimate
  edge: true
